version: '3.1'

services: 
 web:
  build: ./web
  environment: 
   - APACHE_RUN_USER=#1000
   - TZ=Europe/Moscow
  volumes:
   - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
  ports:
   - 8090:80
  working_dir: ${APP_PATH_CONTAINER}
   
 db:
  image: mariadb
  restart: always
  environment:
   - MARIADB_ROOT_PASSWORD:et5dq0Ayp/6H
   - MARIADB_DATABASE:itforit
  environment:
   - TZ=Europe/Moscow
  volumes: 
   - ./database:/var/lib/mysql

 adminter:
  image: adminer
  restart: always
  ports:
   - 6080:8080

 composer:
  image: composer:1.6
  volumes:
   - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
  working_dir: ${APP_PATH_CONTAINER}
  command: composer install   
